# Generated by Django 3.2.6 on 2021-08-18 07:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('age', models.PositiveIntegerField(default=0)),
                ('img_url', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, default='U', max_length=2)),
            ],
            options={
                'managed': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
