# Generated by Django 3.2.6 on 2021-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=7)),
                ('received_date', models.DateTimeField(auto_now=True)),
                ('img_url', models.CharField(blank=True, max_length=40)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
